### ISSUE TITLE
0.28.2 causes runtime error: Cannot use in operator to search for excludeEmptyString

### ISSUE THREAD

**Issue by Albert-Gao** [jquense/yup#799] opened 2020-03-06 07:27 UTC
I have a lib uses `tsdx` to build a module to consume at the backend (AWS Lambda running on Node 12.x), then build with `tsc` by Typescript 3.8.

Today, I updated to `0.28.2` and get the following error message

```javascript
{
    "errorType": "TypeError",
    "errorMessage": "Cannot use 'in' operator to search for 'excludeEmptyString' in At least 8 characters longs, with Lower case letters (a-z), Upper case letters (A-Z), Numbers (0-9) and Special characters (!@#$%^&*()-+_=,.?/;:'\").",
    "stack": [
        "TypeError: Cannot use 'in' operator to search for 'excludeEmptyString' in At least 8 characters longs, with Lower case letters (a-z), Upper case letters (A-Z), Numbers (0-9) and Special characters (!@#$%^&*()-+_=,.?/;:'\").",
        "    at StringSchema.matches (/var/task/node_modules/yup/lib/string.js:107:51)",
        "    at Object.<anonymous> (/var/task/node_modules/@albert-gao/teaming-cloud-shared/dist/teaming-cloud-shared.cjs.development.js:46:14)",
        "    at Module._compile (internal/modules/cjs/loader.js:955:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)",
        "    at Module.load (internal/modules/cjs/loader.js:811:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:723:14)",
        "    at Module.require (internal/modules/cjs/loader.js:848:19)",
        "    at Module._require.o.require (/var/task/serverless_sdk/index.js:9:91865)",
        "    at require (internal/modules/cjs/helpers.js:74:18)",
        "    at Object.<anonymous> (/var/task/node_modules/@albert-gao/teaming-cloud-shared/dist/index.js:7:20)"
    ]
}
```

The line it refers:

```javascript
const ERR_MSG = `At least 8 characters longs, with Lower case letters (a-z), Upper case letters (A-Z), Numbers (0-9) and Special characters (!@#$%^&*()-+_=,.?/;:'").`

const password = string()
  .matches(REGEX.PASSWORD, ERR_MSG)
  .required()
```

The source code is here:
https://github.com/jquense/yup/commit/27e5d684acb7563fa44c4da6baa8e81c94a08c34#diff-57c5960218f1091895b3610a7d779378

by changing from

```javascript
options.hasOwnProperty('excludeEmptyString')
```

to 

```javascript
'excludeEmptyString' in options
```

It causes the error, seems pretty strange.

**Comment by RudiPersson** [comment] 2020-03-06 09:34
Duplicate of #798

**Closed** 2020-03-06 15:14 UTC
