### ISSUE TITLE
Yup members nondeterministically undefined 

### ISSUE THREAD

**Issue by CaptainLexington** [jquense/yup#646] opened 2019-10-03 12:53 UTC
**Describe the bug**
Sometimes we get Airbrake reports from production of errors with Yup functions being `undefined`, in contexts where the code certainly works when we try to use it, in dev or in production. 

Some example snippets:

```
import { string } from 'yup'
...
const passwordValidations = string().min(8).max(72)
```
We will sometimes see this error: `Cannot read property 'constructor' of undefined`

Or perhaps:
```
import { string, object } from 'yup'
...
const schema = object({
  firstName: string(),
  lastName: string()
})
```
with the error: `undefined is not a function`

This can happen just about anywhere we try to use yup. One of our developers believes it may only happen at invocations at the top level scope of each document, i.e. it may only happen when the page initializes and not later, when `yup` is called from inside a function. This, plus the nondeterministic nature of the bug and our near-total inability to reproduce, may suggest a race condition of some kind.

**To Reproduce**
We have never been able to reproduce this bug locally. We only know it exists from Airbrake reports. It is highly nondeterministic. The code otherwise works completely as expected. Yup is the only dependency we have seen exhibit this behavior. 

**Expected behavior**
We expect the calls to work deterministically in all cases, not have a probabilistic chance of failing due to what appear to be failed imports.

**Platform (please complete the following information):**
 - Browser: We've seen this in all the major browsers
 - Version: Both recent versions and older versions

**Comment by jquense** [comment] 2019-10-03 13:05
is there more of a stack trace with these? Unclear which constructor it's looking for at the error site

**Comment by CaptainLexington** [comment] 2019-10-03 15:37
Unfortunately not. We only have source maps for our first-party code; our dependencies remain minified beyond comprehensibility in Airbrake stack traces.

**Comment by skh-** [comment] 2019-11-08 15:07
I am seeing this error as well intermittently without being able to reproduce.  We use Yup for dozens of validations on the site and this particular Search component is the only one where the error seems to occur (and it's at a very low rate).

Below is a stack trace from Rollbar:

```
TypeError: undefined is not a function
1
File "../node_modules/toposort/index.js" line 54 col 22 in toposort
outgoing = Array.from(outgoing);
2
File "../node_modules/toposort/index.js" line 29 col 22 in toposort
if (!visited[i]) visit(nodes[i], i, new Set());
3
File "../node_modules/yup/lib/util/sortFields.js" line 42 col 28 in sortFields
return _toposort.default.array(nodes, edges).reverse();
4
File "../node_modules/yup/lib/object.js" line 244 col 35 in shape
next._nodes = (0, _sortFields.default)(fields, next._excludedEdges);
5
File "App/components/search/index.tsx" line 39 col 29 in Search
const validate = object().shape({
6
File "../node_modules/react-dom/cjs/react-dom.production.min.js" line 3549 col 7 in oa
b = c(d, e);
7
File "../node_modules/react-dom/cjs/react-dom.production.min.js" line 6488 col 11 in eu
e = wh(null, b, d, a, e, c);
8
File "../node_modules/react-dom/cjs/react-dom.production.min.js" line 5530 col 11 in _u
var b = Vj(a.alternate, a, W);
9
File "../node_modules/react-dom/cjs/react-dom.production.min.js" line 5519 col 9 in vu
V = Uj(V);
10
File "../node_modules/react-dom/cjs/react-dom.production.min.js" line 5251 col 11 in su
Mj();

```

Here is the validation function the trace mentions, which is passed to a Formik `validationSchema` prop in a react project.

```
  const validate = object().shape({
    query: string()
      .trim()
      .required(),
  });
```

**Comment by backus** [comment] 2020-03-26 23:25
I've got a pretty small web app and I'm also seeing this error nondeterministically. My error tracker has caught it about 90 times and, interestingly, I've only seen the error for windows users (in either Chrome or Edge).

I wondered if it is actually a gap in my target browsers or something from browserslist, determining what is polyfilled and missing these users. I don't think that's it, but I haven't scrounged up a windows machine yet to investigate further.

**Comment by backus** [comment] 2020-03-27 20:01
@CaptainLexington @skh- Any idea if this bug actually fully breaks the page when your users hit it? I also only see this bug in my bug tracker. It's in the middle of the signup flow for my product which is obviously critical, but when I look into it some of the users are still creating accounts so I'm wondering if it doesn't break the page or if those users are just refreshing or something.

**Comment by backus** [comment] 2020-03-30 19:27
@jquense Would you be open to me putting a bounty of $100 on resolving this issue?

I don't want to put inappropriate pressure on the time you're already generously volunteering (I've done a ton of OSS myself in the past so I know the feeling), but figured I'd check. Thank you for making such a cool and useful resource.

**Comment by skh-** [comment] 2020-03-31 13:22
@CaptainLexington 

> Any idea if this bug actually fully breaks the page when your users hit it? 

I believe it does but I cannot reproduce, so that's not a 100%.  I just checked several occurrences in my reporting software - the error message always seems to be the last interaction.  Since its a SPA, it could very well be breaking.

In my last message I mentioned it was only occurring on one form.  That turned out to be incorrect - I removed Yup from that form and am seeing it on others - although only some, and only sometimes 🤷‍♂ .

It always seems to trigger at an `Object.shape({` line.  Other than that, I can't find any similarities/patterns between the difference places it's occurring.

**Comment by backus** [comment] 2020-03-31 21:45
@skh- Yup, basically identical experience over here. Spent many hours trying to reproduce to no avail. I removed Yup from my app for now since I think this was breaking the page for a non-trivial amount of new user accounts on my app.

Will continue following the issue since I really like Yup and I'm curious what the issue winds up being

**Comment by mschipperheyn** [comment] 2020-05-08 19:28
I have this issue also, I see this code in object.js:
```
var props = this._nodes.concat(Object.keys(value).filter(function (v) {
      return _this3._nodes.indexOf(v) === -1;
}));
```

this._nodes is this array
```
0: "_excludedEdges"
1: "_nodes"
2: "fields"
3: "_type"
4: "_defaultDefault"
5: "_typeError"
6: "_mutate"
7: "transforms"
8: "tests"
9: "_blacklist"
10: "_whitelist"
11: "_exclusive"
12: "_options"
13: "_conditions"
14: "_deps"
```

it then crashes on 
```
field = field.resolve(innerOptions);
```
trying to resolve `_excludedEdges`

**Comment by mschipperheyn** [comment] 2020-05-11 02:25
I was wrong. I just had a mistake in my validation structure. I included an `object().shape()` into another object().shape() like this `object().shape({ ...object().shape() })`

**Comment by eatoncw** [comment] 2021-04-12 15:26
@skh @CaptainLexington - were you able to find a solution for this? We're getting a very similar stack trace on Rollbar too.

**Closed** 2022-08-20 18:35 UTC
