### ISSUE TITLE
Setting locale to default in v1 Beta

### ISSUE THREAD

**Issue by Hawxy** [jquense/yup#1910] opened 2023-02-10 06:02 UTC
Hello, I'm setting up i18n in my project using the v1 beta and I've noticed the library doesn't appear to export the internal locale object, nor is it bundled, so previous fixes like in #814 no longer work. Could this issue be revisited?

Thanks

**Comment by fini** [comment] 2023-02-10 08:44
I am also having problems with yup 1.0.0 failing to import:
`import locale from 'yup/lib/locale'`

**Comment by fini** [comment] 2023-02-10 09:06
It seems to work completely without setting the default locale now.
`// yup.setLocale(locale)`
Not sure why we even did that before, but I'm guessing it caused issues if not?

**Comment by Hawxy** [comment] 2023-02-10 10:07
There's no need to set it out of the box, but if you have a language switcher that needs to set it back to en we need access to the default locale.

**Comment by fini** [comment] 2023-02-10 13:05
> There's no need to set it out of the box, but if you have a language switcher that needs to set it back to en we need access to the default locale.

Ahh yes! That's why I had that code! So we DO need to be able to revert back to default again..

**Comment by Basaingeal** [comment] 2023-02-27 15:22
+1

I have a locale switcher component, and this is preventing me from migrating to `v1.0`

**Comment by jquense** [comment] 2023-02-27 15:25
this should be fixed in the latest version

**Closed by jquense** 2023-02-27 15:25 UTC

**Comment by fini** [comment] 2023-02-27 15:47
> this should be fixed in the latest version

I get a build error using yup 1.0.2 when trying to import locale.

`Module not found: Error: Can't resolve 'yup/lib/locale`

Has the method of getting the default locale changed?

Note: The 1.0.2 release doesn't display on Github under releases, but it does on npm.

**Comment by Basaingeal** [comment] 2023-02-27 15:49
Just checked myself. Looks like:
`import { defaultLocal } from "yup";`
`setLocale(defaultLocale)`

**Comment by fini** [comment] 2023-02-27 15:52
@Basaingeal Yes, confirmed! - it works! 🥳

**Comment by fini** [comment] 2023-02-28 07:59
Confirmed, it does not work ;( Sorry for the confusion.

**Comment by fini** [comment] 2023-02-28 08:03
I tried printing out defaultLocale, and it had changed to the previous language (in this case finnish).

**Comment by fini** [comment] 2023-02-28 08:27
@jquense I think this issue needs to be reopened.

It would be great if you could revert back to being able to use:

`import locale from 'yup/lib/locale'`

Or something similar.

**Comment by jquense** [comment] 2023-02-28 14:21
I guess the issue is we mutate the local object. As a workaround you can import and clone it before updating it. I'll look into making this easier out of the box

**Comment by fini** [comment] 2023-02-28 15:15
> I guess the issue is we mutate the local object. As a workaround you can import and clone it before updating it. I'll look into making this easier out of the box

Yeah I tried doing that a few times today, but it was a crazy path of prop drilling, so my temporary workable solution is that I just made another locale file with the english default data. -- Thanks for a great library, kudos!

**Comment by fini** [comment] 2023-03-17 21:46
> Cloning via spread-operator or `Object.assign` does NOT work.

Nice one, I spend way too long trying to clone and still failed, and ended up just importing English as other with languages, but will definitely try your solution 💪😎

**Comment by fini** [comment] 2023-05-05 19:38
> You have to clone deeper :slightly_smiling_face: 
> 
Nice one!!
