### ISSUE TITLE
TypeScript types: oneOf() should narrow/constrain the type

### ISSUE THREAD

**Issue by chasecaleb** [jquense/yup#1230] opened 2021-01-20 17:26 UTC
**Describe the bug**
`oneOf(..)` constraint should constrain the type to the narrowed values, but it doesn't.

**To Reproduce**
I couldn't make a repro with the codesandbox template because this is a TS-specific issue. However this snippet illustrates the issue:

```typescript
// Works, but overlayed broad type.
const unconstrained: Yup.SchemaOf<string> = Yup.string()
    .required()
    .oneOf(["foo", "bar"]);

// COMPILER ERROR OUTPUT:
// Type 'RequiredStringSchema<string | undefined, Record<string, any>>' is not assignable to type 'BaseSchema<Maybe<"foo">, Record<string, any>, "foo"> | BaseSchema<Maybe<"bar">, Record<string, any>, "bar">'.
//   Type 'RequiredStringSchema<string | undefined, Record<string, any>>' is not assignable to type 'BaseSchema<Maybe<"bar">, Record<string, any>, "bar">'.
//     Types of property '__inputType' are incompatible.
//       Type 'string | undefined' is not assignable to type 'Maybe<"bar">'.
//     Type 'string' is not assignable to type 'Maybe<"bar">'.
const broken: Yup.SchemaOf<"foo" | "bar"> = Yup.string()
    .required()
    .oneOf(["foo", "bar"]);
```

**Expected behavior**
Calling `oneOf()` should constrain the schema's type so that the `broken` value (see example above) compiles. **I'm also open to other ways of accomplishing this if I'm just "doing it wrong"**.

The source (for master at the time of this issue) is part of `BaseSchema`:
https://github.com/jquense/yup/blob/67c96ae7f8fcb59758732b2956ff0b7390f08213/src/schema.ts#L668-L697

...However, I don't think there's a way to constrain it on `BaseSchema` since it uses the polymorphic `this` return type, is there? I think you could override the method in `StringSchema`, etc to specify a stricter return type... kind of awkward, but it would be an improvement. Let me know your thoughts about a solution - **I can make a PR implementing it** if you'd like. I've made a few for you in the past so you know I'm good for it.

**Platform (please complete the following information):**
Current version of Yup (0.32.8). Problem is also present in master as of now (https://github.com/jquense/yup/tree/67c96ae7f8fcb59758732b2956ff0b7390f08213).

**Additional context**
Issue #1165 looks to be related, but there isn't any mention of `as const` in the readme anymore so I'm guessing it's out of date/not relevant anymore.

**Comment by ejose19** [comment] 2021-01-25 04:01
Also, kinda related, when working with ```types | enums``` I would expect the following to work

```ts
type Opt = '1' | '2' | '3';
interface Foo {
  bar: Opt;
}
const opts: Opt[] = ['1', '2', '3'];
const schema: SchemaOf<Foo> = object({
  bar: string().required().oneOf(opts),
});
```

but actually, it errors out with:
```
const schema: ObjectSchemaOf<Foo>
Type 'OptionalObjectSchema<{ bar: RequiredStringSchema<string | undefined, Record<string, any>>; }, Record<string, any>, TypeOfShape<{ bar: RequiredStringSchema<string | undefined, Record<string, any>>; }>>' is not assignable to type 'ObjectSchemaOf<Foo>'.
  The types of 'fields.bar.__inputType' are incompatible between these types.
    Type 'string | undefined' is not assignable to type 'Maybe<Opt>'.
      Type 'string' is not assignable to type 'Maybe<Opt>'.ts(2322)
```

**Comment by P4sca1** [comment] 2021-01-31 13:08
This used to work in older versions of `@types/yup`.

**Comment by janKozie1** [comment] 2021-02-04 13:09
@ejose19 
You should be able to do it with `mixed<Type>()`. Using it like `.mixed<Enum>().oneOf(Object.values(Enum))` worked great for me so far

```js
const schema: yup.SchemaOf<Foo> = yup.object({
  bar: yup.mixed<Opt>().required().oneOf(opts),
});
```

**Comment by TheHolyWaffle** [comment] 2021-03-14 08:54
Duplicate of #1143

**Comment by lgenzelis** [comment] 2021-07-15 02:49
Similar to what @janKozie1 wrote, you can simply write this as
```typescript
const mySchema = yup.object().shape({
  name: yup.string().required(),
  type: yup.mixed<'foo' | 'bar'>().oneOf(['foo', 'bar']).required(),
});
```
The cool thing about it is that, if you were to add an option (`baz`) to the `oneOf` array, typescript would complain automatically:
```typescript
const mySchema = yup.object().shape({
  name: yup.string().required(),
  type: yup.mixed<'foo' | 'bar'>().oneOf(['foo', 'bar', 'baz']).required(),
 // TS2322: Type '"baz"' is not assignable to type 'Reference  | Maybe"foo" | "bar" | undefined>'.
});
```

**Comment by statico** [comment] 2021-12-10 22:47
I still can't get this to work, unfortunately. Any ideas?

[TS Playground link](https://www.typescriptlang.org/play?ssl=11&ssc=179&pln=11&pc=104#code/JYWwDg9gTgLgBAKjgQwM5wJ4FcxwGZQQhwBE2YJAUJQMYQB2q8A8gAoAqAkswHIDKcALxwA2iTwQIJADSkARsigz5yAF4kAuinR1GMSjAxgApnGZgYwBkLiGTEPGY7d+I+lhBzjULQHpfpBJScAA+KkqhKurUukxwqDQAFsYgyDbkAHQQcgBWxjQwABQA3pRwcP7lVdU1tXVVAG5NzQ1lcPTIIMYAXJg4GSDAAB7GACYAPOaWDAB8hQCUWfTGzHiFbFy8fItQxgCOWMC7owuUAL7zlJUAglAA5h7G9PAOtkamAOS7yKMMADYYUTiSTKEgKJSyMFqTQfODAdD0CDwNCoYB3DpyP6mGAQOBgRSdYwwbxwV52T6FABKxjw3ieNGM4yw9AA1oiAO70GaRACyyAwXnGwOCYShEVFCnUkWZoxpwGWoxm8xEGg+GSuAXK7GSbxMcC+xh+-0BYiCoPB5uhqrh6ANRvoANhyHoozgNGdiPgXm0qPRY1suJgOpAWBgyEx2Pe+qpNLp9AZTNZHK5vP5guFJEiYszEuh0pdcoVSpVasKACYAMwAFgArPMgA)

```typescript
import * as yup from "yup"

const OPTIONS = ["foo", "bar", "baz"] as const
type Option = typeof OPTIONS[number] // "foo" | "bar" | "baz"

const schema = yup.object({
  //                              vvvvvvv
  name: yup.mixed<Option>().oneOf(OPTIONS).required()
})
// Argument of type 'readonly ["foo", "bar", "baz"]' is not assignable to parameter of type '(Reference<unknown> | Maybe<"foo" | "bar" | "baz" | undefined>)[]'.
//   The type 'readonly ["foo", "bar", "baz"]' is 'readonly' and cannot be assigned to the mutable type '(Reference<unknown> | Maybe<"foo" | "bar" | "baz" | undefined>)[]'.(2345)
```

**Comment by statico** [comment] 2021-12-10 22:50
Removing `as const` fixes it, but what I'm really trying to do is also get the type back out using `yup.Asserts`. That doesn't work, unfortunately:

```typescript
type SchemaData = yup.Asserts<typeof schema>
// type SchemaData = { name: string; }
```

**Comment by calag4n** [comment] 2022-02-19 11:28
> I still can't get this to work, unfortunately. Any ideas?
> 
> [TS Playground link](https://www.typescriptlang.org/play?ssl=11&ssc=179&pln=11&pc=104#code/JYWwDg9gTgLgBAKjgQwM5wJ4FcxwGZQQhwBE2YJAUJQMYQB2q8A8gAoAqAkswHIDKcALxwA2iTwQIJADSkARsigz5yAF4kAuinR1GMSjAxgApnGZgYwBkLiGTEPGY7d+I+lhBzjULQHpfpBJScAA+KkqhKurUukxwqDQAFsYgyDbkAHQQcgBWxjQwABQA3pRwcP7lVdU1tXVVAG5NzQ1lcPTIIMYAXJg4GSDAAB7GACYAPOaWDAB8hQCUWfTGzHiFbFy8fItQxgCOWMC7owuUAL7zlJUAglAA5h7G9PAOtkamAOS7yKMMADYYUTiSTKEgKJSyMFqTQfODAdD0CDwNCoYB3DpyP6mGAQOBgRSdYwwbxwV52T6FABKxjw3ieNGM4yw9AA1oiAO70GaRACyyAwXnGwOCYShEVFCnUkWZoxpwGWoxm8xEGg+GSuAXK7GSbxMcC+xh+-0BYiCoPB5uhqrh6ANRvoANhyHoozgNGdiPgXm0qPRY1suJgOpAWBgyEx2Pe+qpNLp9AZTNZHK5vP5guFJEiYszEuh0pdcoVSpVasKACYAMwAFgArPMgA)
> 
> ```ts
> import * as yup from "yup"
> 
> const OPTIONS = ["foo", "bar", "baz"] as const
> type Option = typeof OPTIONS[number] // "foo" | "bar" | "baz"
> 
> const schema = yup.object({
>   //                              vvvvvvv
>   name: yup.mixed<Option>().oneOf(OPTIONS).required()
> })
> // Argument of type 'readonly ["foo", "bar", "baz"]' is not assignable to parameter of type '(Reference<unknown> | Maybe<"foo" | "bar" | "baz" | undefined>)[]'.
> //   The type 'readonly ["foo", "bar", "baz"]' is 'readonly' and cannot be assigned to the mutable type '(Reference<unknown> | Maybe<"foo" | "bar" | "baz" | undefined>)[]'.(2345)
> ```

Same problem here, any idea ?

**Comment by JonRC** [comment] 2022-05-10 10:15
> @ejose19 You should be able to do it with `mixed<Type>()`. Using it like `.mixed<Enum>().oneOf(Object.values(Enum))` worked great for me so far
> 
> ```js
> const schema: yup.SchemaOf<Foo> = yup.object({
>   bar: yup.mixed<Opt>().required().oneOf(opts),
> });
> ```

it worked for me.

**Comment by karlhorky** [comment] 2022-05-27 14:07
Opened a PR to the types here: #1675

**Comment by linkb15** [comment] 2022-07-26 04:28
+1

**Closed** 2022-08-20 18:40 UTC

**Comment by karlhorky** [comment] 2022-08-22 21:48
@jquense why did you close this? Has it been implemented in one of the latest betas? 

If that's the case, maybe #1675 is obsolete now and should be closed?

**Comment by jquense** [comment] 2022-08-22 21:56
Yes it's obsolete now

**Comment by karlhorky** [comment] 2022-08-22 23:27
Ok, looking a bit closer at what my original demo from #1675, it seems there is still broken behavior, also in `1.0.0-beta.7`: https://github.com/jquense/yup/pull/1675#issuecomment-1223320504

So maybe this issue (#1230) should be reopened - or #1675 or another fix merged + published.

**Comment by MasterRedStorm** [comment] 2024-04-25 15:35
still seems to be an issue

**Comment by intercepted16** [comment] 2024-06-24 11:53
Hi, it still seems to be an issue.
