### ISSUE TITLE
excludeEmptyString

### ISSUE THREAD

**Issue by easypaymentsfr** [jquense/yup#802] opened 2020-03-06 14:04 UTC
I have following error when i want to build my NextJs App

![Sans titre](https://user-images.githubusercontent.com/61663559/76089378-d5df6f80-5fb9-11ea-9885-61b332076f45.png)

When i replace https://github.com/jquense/yup/blob/b5b627be01e8c428bd55ad471a03db8c877d9122/src/string.js#L79

by

https://github.com/jquense/yup/blob/053e95f598b6e0bfe9c2042e237ea37cdcf74382/src/string.js#L79-L83

I do not have any problems..

**Comment by jreyes33** [comment] 2020-03-06 14:59
Duplicate of #798. Rolling back to v0.28.1 is a solution for now.

**Closed** 2020-03-06 15:14 UTC

**Comment by JClackett** [comment] 2021-11-03 10:52
@jquense This error seems to be popping up again for a lot of people using the new Next.js 12.x release when using their new Swc minifier. 

Here is an [issue](https://github.com/vercel/next.js/issues/30429) in the next.js repo.

Not sure if this is a Next.js issue or something with Yup combined with the new version of Next.js.
