### ISSUE TITLE
mixed.when() runs twice per field

### ISSUE THREAD

**Issue by plashenkov** [jquense/yup#1490] opened 2021-10-15 02:02 UTC
Hi!

**Describe the bug**

I am trying to adjust the schema based on sibling fields, as well as parent fields.

> My validated object has an array of objects which may have `delete: true` field. This means: this subobject has to be deleted (later from DB), so no other fields of this particular subobject are required. When the `delete` field is unset, we need to `require()` some fields, and assign `default()` values for some other fields.
>
> These deletable objects have also child array with object with the same logic. So, for these deep objects I have to check not only their `delete` field, but also their parent's `delete` field.
>
> (Actually, logic is a little more complex, but that's enough to describe the problem).

When I use `when()` on a field, I can see that in reality it runs twice for each field. The first time it runs it doesn't provide the `from` array, and generally `when()` context is really scanty. So, the only option for this run is to return untouched schema, as it was passed to my callback. The next run of `when()` provides really complete data — I can do everything I need.

But the problem is that the first run affects the final schema, and I cannot do anything with this.
For example, if I return the untouched schema during the first run, and later I set `default('some_value')`, then the final schema doesn't have this `default()`: if the input object doesn's have the field, the result object will not have the field either, despite of the fact it has to have some default value now.

To workaround this, I tried to always set `default()` inside the first run of `when()`, and later, in the second run, cancel it for some fields by setting `default(undefined)`. But: now finally every field is marked as `default('some_value')`, and it looks like `default(undefined)` doesn't have any power.

So, `default()` from the first run has a priority over the `default()` from second run.
But: `require()` from the second run has priority over the `require()` from first run.

So, the question is: is it really correct that `when()` fires twice? Or maybe it is a bug?
If this behavior is still correct, how to skip the first run? Because it doesn't provide enough data (any semantic data really) yet to calculate and return the valid schema. Only the second run allows it.

**To Reproduce**

I'll do my best to provide a runnable test case using the code sandbox later if you need it.

**Expected behavior**

I expect `when()` to be run once with all the data (the `from` array, etc).

**Platform:**
 - Node.js v16

**Comment by IdkMan2Usertive** [comment] 2022-09-30 12:43
Exactly the same issue occurs for `transform(...)` method.

**Comment by JohnnyTheTank** [comment] 2023-02-10 12:40
confirmed

**Comment by jquense** [comment] 2023-02-10 14:03
Yes it can run twice, there is no guarantee that methods will run exactly once per validation. This isn't really a bug more of performance tuning opportunity (one that is already noted in a comment in the code but is not simple to fix)

**Comment by IdkMan2Usertive** [comment] 2023-02-10 14:07
It's really misleading when `transform()` method is called twice with different arguments for each call. This type of implementation exposes the user's callback to errors, expecting the same shape of arguments for each call.

**Comment by jquense** [comment] 2023-02-10 14:12
they should run with the same arguments, please post a reproduction of the case where it doesn't, i'd be happy to either fix or explain

**Comment by JohnnyTheTank** [comment] 2023-02-10 15:46
for me it ran twice:
```
const handleFileChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setFieldTouched('file', true) 
    setFieldValue('file', event.target.files?.[0] ?? null)
  }
```
one time for the `setFieldTouched` and one time for `setFieldValue`

**Comment by jquense** [comment] 2023-02-10 19:30
I don't know what those functions are or what they do. but all `when` functions run every time you use the schema, b/c the result is based on the runtime input

**Comment by JohnnyTheTank** [comment] 2023-02-10 20:51
> I don't know what those functions are or what they do. but all `when` functions run every time you use the schema, b/c the result is based on the runtime input

those are formik functions. but it's not the fault of yup. btw, great tool!

**Comment by IdkMan2Usertive** [comment] 2023-02-15 13:25
@jquense

> Exactly the same issue occurs for transform(...) method.

> Yes it can run twice, there is no guarantee that methods will run exactly once per validation. This isn't really a bug more of performance tuning opportunity (one that is already noted in a comment in the code but is not simple to fix)

> It's really misleading when transform() method is called twice with different arguments for each call. This type of implementation exposes the user's callback to errors, expecting the same shape of arguments for each call.

> they should run with the same arguments, please post a reproduction of the case where it doesn't, i'd be happy to either fix or explain

I have spent a few hours trying to reproduce this issue, with no luck. I swear I did not make this up 😄.

Most probably that this issue has been already fixed X versions ago, as I was using a very old version of this lib at the time I wrote [this comment](https://github.com/jquense/yup/issues/1490#issuecomment-1263526871). Alternatively, I may have made a related bug that has been fixed by me in the meantime, who knows? Anyway, everything works now as intended. I apologize for the confusion and thank you very much for your honest work on this lib.

**Comment by ibnumusyaffa** [comment] 2023-12-31 15:04
```js
import yup from "yup"

export const userSchema = yup.object({
  count: yup.number().when("name", ([name], schema) => {
    console.log(name)
    return name ? schema.min(5) : schema.min(0)
  }),
  name: yup.string().min(2).required(),
  email: yup.string().email().required(),
})

await schema.validate({ count: 1, name: "john" }, { abortEarly: false })

```

just need to clarify, the console log in count property called twice, is this considered not a bug ?

**Closed** 2024-01-09 17:39 UTC
Labels: help wanted
